version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_URI=postgresql://app_user:app_password@localhost:5432/microservices
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - DB_NAME=microservices
      - DB_HOST=localhost
      - DB_PORT=5432